language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
  - rust: nightly
addons:
    apt:
      packages:
        - g++-4.8
script:
  - cargo build --verbose
  - cargo test --verbose
  - python run-tests.py
  - python run-tests.py -c
