language: rust
cache: cargo
rust:
  - nightly
before_script:
  - rustup component add rustfmt-preview
addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-4.9
        - g++-4.9
env:
  - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
script:
  - cargo fmt --all -- --check
  - cargo build --verbose
  - cargo test --verbose
  - python test.py -v
