language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
  - rust: nightly
addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-4.9
        - g++-4.9
env:
  - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
script:
  - cargo build --verbose
  - cargo test --verbose
  - python test.py
  - python test.py -c
