[package]
name = "cbindgen"
description = "A tool for generating C bindings to Rust code."
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>", "Kartikaya Gupta <kats@mozilla.com>", "Ryan Hunt <rhunt@eqrion.net>"]
license = "MPL-2.0"
version = "0.1.10"
exclude = ["compile-tests/**"]
repository = "https://github.com/rlhunt/cbindgen/"

[badges]
travis-ci = { repository = "rlhunt/cbindgen" }

[dependencies]
clap = "2"
log = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

toml = "0.3"

[dependencies.syn]
version = "0.11"
features = ["full"]

[[bin]]
name = "cbindgen"
path = "src/main.rs"

[lib]
name = "cbindgen"
path = "src/lib.rs"
