[package]
name = "cbindgen"
description = "A tool for generating C bindings to Rust code."
license = "MPL-2.0"
version = "0.1.2"
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>", "Kartikaya Gupta <kats@mozilla.com>", "Ryan Hunt <rhunt@eqrion.net>"]
repository = "https://github.com/rlhunt/cbindgen/"
exclude = ["examples/**"]

[dependencies]
clap = "2.23.2"
log = "0.3"

[dependencies.syn]
version = "0.11.8"
features = ["full"]
